moving from github.com/vilasle/yp-metrics
vilasle/metrics pull request #1
Opened 2024-12-03 22:58 UTC by vilasle

2024-12-05 23:26 UTC, avhitrov requested changes
- Гонки на сервере
- Неверное формирование агентом запросов к серверу
- Недоформатированный код
- Прочие замечания в комментариях к PR

Скорее всего, после исправления агента найдутся еще ошибки во взаимодействии сервисов. Предлагаю сразу обратить внимание на работу счетчика. На сервере он должен расти линейно и отображать количество сделанных проходов по сбору данных агентом.

2024-12-05 23:26 UTC, avhitrov commented on cmd/agent/main.go
> +	for run := true; run; {
```suggestion
	for {
```

2024-12-05 23:26 UTC, avhitrov commented on internal/metric/error.go
Файл следует прогнать через `go fmt internal/metric/error.go`, либо использовать редактор с автоматическим форматированием кода (VS Code или GoLand)

2024-12-05 23:26 UTC, avhitrov commented on internal/repository/memory/counter.go
> +	metrics map[string][]model.Counter
Мапа – структура потоконебезопасная. Это означает, что в конкурентной среде (а http-сервер априори является конкурентным приложением, так как открывает по горутине на каждый входящий запрос) любые обращения к ней должны оборачиваться блокировками. В Go для этого существуют мьютексы (sync.Mutex или sync.RWMutex). Кроме того, можно использовать потокозащищенные структуры, вроде sync.Map.

Подробнее: https://t.me/bushigo/24

Продемонстрировать в настоящий момент не могу, так как агент отправляет данные в кривом формате.

2024-12-05 23:26 UTC, avhitrov commented on internal/service/agent/sender/rest/specific.go
> +	req, err := http.NewRequest(http.MethodPost, u.String(), nil)
В результате `u.String()` формирует кривой путь, что порождает запросы от агента вида:
```
2024/12/06 02:01:18 "POST http://localhost:8080/%5Cupdate%5Cgauge%5CGCSys%5C2482928 HTTP/1.1" from [::1]:57016 - 404 19B in 0s
2024/12/06 02:01:18 "POST http://localhost:8080/%5Cupdate%5Cgauge%5CHeapIdle%5C3653632 HTTP/1.1" from [::1]:57017 - 404 19B in 0s
2024/12/06 02:01:18 "POST http://localhost:8080/%5Cupdate%5Cgauge%5CHeapObjects%5C22292 HTTP/1.1" from [::1]:57018 - 404 19B in 0s
2024/12/06 02:01:18 "POST http://localhost:8080/%5Cupdate%5Cgauge%5CMSpanSys%5C163200 HTTP/1.1" from [::1]:57019 - 404 19B in 0s
2024/12/06 02:01:18 "POST http://localhost:8080/%5Cupdate%5Cgauge%5CStackSys%5C753664 HTTP/1.1" from [::1]:57020 - 404 19B in 0s
2024/12/06 02:01:18 "POST http://localhost:8080/%5Cupdate%5Cgauge%5CRandomValue%5C0.09064677088383438 HTTP/1.1" from [::1]:57021 - 404 19B in 0s
2024/12/06 02:01:18 "POST http://localhost:8080/%5Cupdate%5Cgauge%5CMCacheInuse%5C14016 HTTP/1.1" from [::1]:57022 - 404 19B in 0s
2024/12/06 02:01:18 "POST http://localhost:8080/%5Cupdate%5Cgauge%5CMCacheSys%5C16352 HTTP/1.1" from [::1]:57023 - 404 19B in 0s
2024/12/06 02:01:18 "POST http://localhost:8080/%5Cupdate%5Cgauge%5CPauseTotalNs%5C0 HTTP/1.1" from [::1]:57024 - 404 19B in 0s
2024/12/06 02:01:18 "POST http://localhost:8080/%5Cupdate%5Cgauge%5CSys%5C12472320 HTTP/1.1" from [::1]:57025 - 404 19B in 0s
2024/12/06 02:01:18 "POST http://localhost:8080/%5Cupdate%5Cgauge%5CHeapAlloc%5C3202824 HTTP/1.1" from [::1]:57026 - 404 19B in 0s
2024/12/06 02:01:18 "POST http://localhost:8080/%5Cupdate%5Cgauge%5CHeapSys%5C7634944 HTTP/1.1" from [::1]:57027 - 404 19B in 0s
2024/12/06 02:01:18 "POST http://localhost:8080/%5Cupdate%5Cgauge%5CLookups%5C0 HTTP/1.1" from [::1]:57028 - 404 19B in 0s
2024/12/06 02:01:18 "POST http://localhost:8080/%5Cupdate%5Cgauge%5CHeapInuse%5C3981312 HTTP/1.1" from [::1]:57029 - 404 19B in 1ms
2024/12/06 02:01:18 "POST http://localhost:8080/%5Cupdate%5Cgauge%5CLastGC%5C1733439628611364000 HTTP/1.1" from [::1]:57030 - 404 19B in 0s
2024/12/06 02:01:18 "POST http://localhost:8080/%5Cupdate%5Cgauge%5CMallocs%5C141855 HTTP/1.1" from [::1]:57031 - 404 19B in 0s
2024/12/06 02:01:18 "POST http://localhost:8080/%5Cupdate%5Cgauge%5CNextGC%5C4194304 HTTP/1.1" from [::1]:57032 - 404 19B in 0s
2024/12/06 02:01:18 "POST http://localhost:8080/%5Cupdate%5Cgauge%5COtherSys%5C1411745 HTTP/1.1" from [::1]:57033 - 404 19B in 0s
2024/12/06 02:01:18 "POST http://localhost:8080/%5Cupdate%5Cgauge%5CAlloc%5C3202824 HTTP/1.1" from [::1]:57034 - 404 19B in 1.0005ms
2024/12/06 02:01:18 "POST http://localhost:8080/%5Cupdate%5Cgauge%5CBuckHashSys%5C9487 HTTP/1.1" from [::1]:57035 - 404 19B in 0s
2024/12/06 02:01:18 "POST http://localhost:8080/%5Cupdate%5Cgauge%5CFrees%5C119563 HTTP/1.1" from [::1]:57036 - 404 19B in 0s
2024/12/06 02:01:18 "POST http://localhost:8080/%5Cupdate%5Cgauge%5CStackInuse%5C753664 HTTP/1.1" from [::1]:57037 - 404 19B in 0s
2024/12/06 02:01:18 "POST http://localhost:8080/%5Cupdate%5Cgauge%5CTotalAlloc%5C19151376 HTTP/1.1" from [::1]:57038 - 404 19B in 0s
```
Сервер на них ожидаемо отвечат 404. Для проверки достаточно скомпилировать и запустить в разных консолях (для винды может быть использован powershell или cmd).

2024-12-05 23:26 UTC, avhitrov commented on cmd/server/main.go
> +	server.Register("/value/", methods(http.MethodGet), contentTypes(), rest.DisplayMetric(svc))
```suggestion
	server.Register("/value/{type}/{name}", methods(http.MethodGet), contentTypes(), rest.DisplayMetric(svc))
```
И дальше разбирать штатными методами.

2024-12-05 23:26 UTC, avhitrov commented on cmd/server/main.go
> +	server.Register("/update/", methods(http.MethodPost), contentTypes(), rest.UpdateMetric(svc))
```suggestion
	server.Register("/update/{type}/{name}/{value}", methods(http.MethodPost), contentTypes(), rest.UpdateMetric(svc))
```

2024-12-10 02:35 UTC, vilasle commented on cmd/agent/main.go
> +	for run := true; run; {
как и цикла предлагает выйти? return? break? os.Exit(0)?

2024-12-12 16:23 UTC, avhitrov requested changes
Практически все замечания учтены, но как только возникла возможность нормально  протестировать одновременную работу агента и сервера, выплыли новые. Отображены в комментариях к коду и, в основном, касаются поведения метрики типа "счетчик".

Upd: При выходе из сервера вылетело предупреждение о найденных гонках. Вот лог для анализа:
```
==================
WARNING: DATA RACE
Read at 0x00c00009e2c8 by main goroutine:
  main.main()
      C:/work/src/github.com/vilasle/metrics/cmd/server/main.go:71 +0xb04

Previous write at 0x00c00009e2c8 by goroutine 9:
  github.com/vilasle/metrics/internal/transport/rest/server.(*HTTPServer).Start()
      C:/work/src/github.com/vilasle/metrics/internal/transport/rest/server/server.go:50 +0xdb
  main.main.func2()
      C:/work/src/github.com/vilasle/metrics/cmd/server/main.go:63 +0x44

Goroutine 9 (running) created at:
  main.main()
      C:/work/src/github.com/vilasle/metrics/cmd/server/main.go:62 +0xade
==================
```

2024-12-12 16:23 UTC, avhitrov commented on cmd/agent/main.go
> +	for run := true; run; {
Лучше `break`, так как после может появиться еще какая-то логика, связанная с graceful shutdown. Но на текущем этапе сработает любой вариант.

2024-12-12 16:23 UTC, avhitrov commented on cmd/agent/agent.go
> +	}
В случае успешной отправки всех метрик на сервер, в агенте необходимо сбрасывать счетчик. Физическое значение счетчика - отображение количества проходов агента по сбору метрик. И его значение на сервере должно расти линейно. В текущей реализации значение счетчика на сервере растет в сложной геометрической прогрессии.

2024-12-12 16:23 UTC, avhitrov commented on internal/transport/rest/server/handler.go
> +		d := cleanUselessData(r.Context())
Для чего такая странная логика? Значения из раутера однозначно интерпретируются и однозначно заполняются в случае удовлетворения заданному шаблону.

2024-12-12 17:06 UTC, vilasle commented on internal/transport/rest/server/handler.go
> +		d := cleanUselessData(r.Context())
Если имеете ввиду, то что хэнделер возвращает другой хэндлер, то это не странно. В следующих спринтах предусмотрены работы с базами данных и с файловой системой, что уже может возвращаться ошибку. То есть появляется ситуация ошибкок клиента и ошибок сервера. И плодить конструкции типа
```v, err := doSmt()```
```if err != nil {```
```     w.WriteHeader(400)```
```     return```
```}```
вместо
```var v any```
```var err error```
```if v, err = doSmt(); err != nil {```
```     return err```
```}```
кажется более странным. Не лучше ли чтобы хэндлер отвечал за логику, а с ошибками и ответами разбирался middleware?  В таком случае достаточно будет обернуть эту функцию в какой нибудь ```type HandlerWithError struct {}``` который реализируется интерфейс ```http.Handler```
Если я неправильно рассуждаю, подскажите пожалуйста, в чем ошибаюсь и как будет лучше?

2024-12-16 19:13 UTC, avhitrov commented on internal/transport/rest/server/server.go
> +	s.stateMx.Unlock()
В данном процессе конкурентность отсутствует. Он запускается один раз в один поток. Поэтому мьютекс ни здесь, ни в последующем defer не нужен. Конкурентно запускаются только функции-обработчики хендлеров.

2024-12-16 19:13 UTC, avhitrov commented on internal/transport/rest/server/handler.go
> +		d := cleanUselessData(r.Context())
Я к тому, что от chi прилетают вполне себе именованные параметры, которые код cleanUselessData превращает в список. В котором дальше делается псевдопоиск по ключу, базирующийся на позиции в списке. 
Чем это оптимальнее, чем просто вызов?
```
chi.URLParam(r, "type")
```
Кроме того, конструкция:
```
	v := ctx.Value("type")
	_ = v
```
кажется, вообще лишена смысла.

2024-12-16 19:16 UTC, avhitrov commented on internal/transport/rest/server/handler.go
> +		d := cleanUselessData(r.Context())
Ну и по поводу мидлваре - обычно функция мидлвари - единообразно обслуживать все или группу хендлеров. Например, обеспечив сжатие-разжатие gzip или общее логирование с таймингами выполнения. Мидлварь, применимая к одному-двум хендлерам, особого смысла не имеет, зато вполне себе сжирает ресурсы на дополнительный контекст-свитчинг и копирование переменных.

2024-12-16 19:20 UTC, avhitrov approved these changes
Даю аппрув, так как функционально связка приложений работает верно. Есть комментарии, в том числе в рамках дискуссии, рекомендую перед мержем в main ознакомиться и, возможно, что-то поправить в дальнейших итерациях.

2024-12-16 19:40 UTC, merged